### PR TITLE
Add autogen.sh step

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please update circle

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please update circle

**Comment by marcelotrevisani** [comment]
I think we can remove m4 as build requirement, let's see

**Comment by nsoranzo** [comment]
> I think we can remove m4 as build requirement, let's see

It comes as run requirement of `automake` anyway, nothing will change in practice.

**Comment by nsoranzo** [comment]
Anything else you want to add to this PR? In the end there is no CI change.

**Comment by marcelotrevisani** [comment]
I ran to update the keys in the Linux CI
Because it seems that it is failing because of that. Let's see it solved

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please update circle

**Comment by nsoranzo** [comment]
@conda-forge-admin, please rerender

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
